/*
 * test_embedded.c — GC_EMBEDDED mode tests
 *
 * Validates: decode + gc_from/gc_to with static-only memory.
 * gc_set/gc_encode/gc_free are NOT available and must not compile.
 *
 * Test payloads are pre-generated by the default-mode encoder
 * and hardcoded as byte arrays.
 */

#define GC_EMBEDDED
#define GRIDCODEC_IMPLEMENTATION
#include "gridcodec.h"

#include <stdio.h>
#include <assert.h>

/* ================================================================
 *  Pre-generated payloads (from default-mode encoder)
 *
 *  payload_l1_only:  FN->PM and JO->FN, Layer 1 only
 *  payload_l1l2:     FN31->PM02 and JO22->FN31, Layer 1 + Layer 2
 * ================================================================ */

static const uint8_t payload_l1_only[] = {
    0x01,0x00,0x20,0x02,0x00,0x80,0x01,0x02,0x08,0x00,0x0c,0x09,
    0x06,0x06
};
static const int payload_l1_only_len = 14;

static const uint8_t payload_l1l2[] = {
    0x01,0x01,0x20,0x02,0x00,0x80,0x01,0x02,0x08,0x00,0x0c,0x09,
    0x06,0x06,0x08,0x08,0x10,0x00,0x01,0x01,0x01,0x01,0x04,0x10,
    0x80,0x80,0x00,0x01,0x01,0x01
};
static const int payload_l1l2_len = 30;

/* ================================================================
 *  Tests
 * ================================================================ */

static void test_embedded_memory(void) {
    printf("  sizeof(gc_matrix_t) [EMBEDDED] = %zu bytes (%.1f KB)\n",
           sizeof(gc_matrix_t), (double)sizeof(gc_matrix_t) / 1024.0);
    printf("    field_bits[%d] = %d bytes (Layer 1 only, fixed)\n",
           GC_FIELD_MATRIX_BYTES, GC_FIELD_MATRIX_BYTES);
    printf("    No Layer 2, no dynamic memory, no <stdlib.h>\n");
}

static void test_embedded_decode_l1(void) {
    printf("  test_decode_l1_only...");

    gc_matrix_t m;
    gc_init(&m);
    int consumed = gc_decode(payload_l1_only, payload_l1_only_len, &m);
    assert(consumed == payload_l1_only_len);

    /* FROM "FN" should return PM */
    int results[64];
    int n = gc_from(&m, "FN", results, 64);
    assert(n == 1);
    char fname[3];
    gc_field_name(results[0], fname);
    assert(fname[0] == 'P' && fname[1] == 'M');

    /* TO "FN" should return JO */
    n = gc_to(&m, "FN", results, 64);
    assert(n == 1);
    gc_field_name(results[0], fname);
    assert(fname[0] == 'J' && fname[1] == 'O');

    /* FROM "JO" should return FN */
    n = gc_from(&m, "JO", results, 64);
    assert(n == 1);
    gc_field_name(results[0], fname);
    assert(fname[0] == 'F' && fname[1] == 'N');

    /* FROM "PM" should return nothing (PM is only a destination) */
    n = gc_from(&m, "PM", results, 64);
    assert(n == 0);

    printf(" OK\n");
}

static void test_embedded_decode_l1l2(void) {
    printf("  test_decode_l1l2_skip_layer2...");

    /* Payload has L2 flag set. Embedded mode should decode L1 and skip L2. */
    assert(payload_l1l2[1] & GC_FLAG_LAYER2);

    gc_matrix_t m;
    gc_init(&m);
    int consumed = gc_decode(payload_l1l2, payload_l1l2_len, &m);
    assert(consumed == payload_l1l2_len);

    /* L1 should be intact: FN->PM and JO->FN */
    int results[64];
    int n = gc_from(&m, "FN", results, 64);
    assert(n == 1);
    char fname[3];
    gc_field_name(results[0], fname);
    assert(fname[0] == 'P' && fname[1] == 'M');

    n = gc_to(&m, "FN", results, 64);
    assert(n == 1);
    gc_field_name(results[0], fname);
    assert(fname[0] == 'J' && fname[1] == 'O');

    printf(" OK (L2 data skipped, consumed all %d bytes)\n", consumed);
}

static void test_embedded_4char_degrades(void) {
    printf("  test_4char_query_degrades_to_field...");

    gc_matrix_t m;
    gc_init(&m);
    gc_decode(payload_l1_only, payload_l1_only_len, &m);

    /* 4-char query in embedded mode returns field-level results */
    int results[64];
    int n = gc_from(&m, "FN31", results, 64);
    assert(n == 1);
    /* Result is a field index, not a grid index */
    assert(results[0] < GC_FIELDS);
    char fname[3];
    gc_field_name(results[0], fname);
    assert(fname[0] == 'P' && fname[1] == 'M');

    n = gc_to(&m, "FN31", results, 64);
    assert(n == 1);
    assert(results[0] < GC_FIELDS);
    gc_field_name(results[0], fname);
    assert(fname[0] == 'J' && fname[1] == 'O');

    printf(" OK\n");
}

static void test_embedded_no_encode_api(void) {
    printf("  test_no_encode_api...");

    /* Verify gc_free/gc_set/gc_encode do NOT exist.
     * Uncommenting any line below must cause a compile error:
     *
     *   gc_matrix_t m; gc_init(&m);
     *   gc_free(&m);                          // ERROR
     *   gc_set(&m, "FN31", "PM02");           // ERROR
     *   gc_encode(&m, buf, sizeof(buf));       // ERROR
     */

    printf(" OK (gc_set/gc_encode/gc_free correctly absent)\n");
}

/* ================================================================
 *  Main
 * ================================================================ */

int main(void) {
    printf("=== GridCodec Test Suite (GC_EMBEDDED mode) ===\n\n");

    printf("[Memory layout]\n");
    test_embedded_memory();

    printf("\n[Decode + Query tests]\n");
    test_embedded_decode_l1();
    test_embedded_decode_l1l2();
    test_embedded_4char_degrades();
    test_embedded_no_encode_api();

    printf("\n=== All embedded tests passed ===\n");
    return 0;
}
